// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start';
import { supabase } from './client';

export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const {
      data: { session },
    } = await supabase.auth.getSession();

    const headers: HeadersInit = {};
    if (session?.access_token) {
      headers['Authorization'] = `Bearer ${session.access_token}`;
    }

    return next({
      context: { supabaseSession: session },
      sendContext: { supabaseSession: session },
      headers,
    });
  },
);
